# publish new changes coming from main -> publish branch.
name: publish

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out into publish branch
      - uses: actions/checkout@v3
        with:
          ref: publish

      # Runs a single command using the runners shell
      - name: Update publish branch
        run: |
          git merge main -m "Merged main -> publish on $(date +%F)"

      # Runs a set of commands using the runners shell
      - name: Push the publish branch
        run: |
          git push origin publish
